schema = {
    "type": "array",
    "items": {
        "type": "object",
        "properties": {
            "huc12": {"type": "string", "pattern": "^[0-9]{1,12}$"},
            "tpload_hp": {"type": "number"},
            "tpload_crop": {"type": "number"},
            "tpload_wooded": {"type": "number"},
            "tpload_open": {"type": "number"},
            "tpload_barren": {"type": "number"},
            "tpload_ldm": {"type": "number"},
            "tpload_mdm": {"type": "number"},
            "tpload_hdm": {"type": "number"},
            "tpload_wetland": {"type": "number"},
            "tpload_farman": {"type": "number"},
            "tpload_tiledrain": {"type": "number"},
            "tpload_streambank": {"type": "number"},
            "tpload_subsurface": {"type": "number"},
            "tpload_pointsource": {"type": "number"},
            "tpload_septics": {"type": "number"},
            "tnload_hp": {"type": "number"},
            "tnload_crop": {"type": "number"},
            "tnload_wooded": {"type": "number"},
            "tnload_open": {"type": "number"},
            "tnload_barren": {"type": "number"},
            "tnload_ldm": {"type": "number"},
            "tnload_mdm": {"type": "number"},
            "tnload_hdm": {"type": "number"},
            "tnload_wetland": {"type": "number"},
            "tnload_farman": {"type": "number"},
            "tnload_tiledrain": {"type": "number"},
            "tnload_streambank": {"type": "number"},
            "tnload_subsurface": {"type": "number"},
            "tnload_pointsource": {"type": "number"},
            "tnload_septics": {"type": "number"},
            "tssload_hp": {"type": "number"},
            "tssload_crop": {"type": "number"},
            "tssload_wooded": {"type": "number"},
            "tssload_open": {"type": "number"},
            "tssload_barren": {"type": "number"},
            "tssload_ldm": {"type": "number"},
            "tssload_mdm": {"type": "number"},
            "tssload_hdm": {"type": "number"},
            "tssload_wetland": {"type": "number"},
            "tssload_tiledrain": {"type": "number"},
            "tssload_streambank": {"type": "number"}
        },
        "additionalProperties": False,
        "required": [
            "huc12",
            "tpload_hp",
            "tpload_crop",
            "tpload_wooded",
            "tpload_open",
            "tpload_barren",
            "tpload_ldm",
            "tpload_mdm",
            "tpload_hdm",
            "tpload_wetland",
            "tpload_farman",
            "tpload_tiledrain",
            "tpload_streambank",
            "tpload_subsurface",
            "tpload_pointsource",
            "tpload_septics",
            "tnload_hp",
            "tnload_crop",
            "tnload_wooded",
            "tnload_open",
            "tnload_barren",
            "tnload_ldm",
            "tnload_mdm",
            "tnload_hdm",
            "tnload_wetland",
            "tnload_farman",
            "tnload_tiledrain",
            "tnload_streambank",
            "tnload_subsurface",
            "tnload_pointsource",
            "tnload_septics",
            "tssload_hp",
            "tssload_crop",
            "tssload_wooded",
            "tssload_open",
            "tssload_barren",
            "tssload_ldm",
            "tssload_mdm",
            "tssload_hdm",
            "tssload_wetland",
            "tssload_tiledrain",
            "tssload_streambank"]
    }
}

huc12_returned_column_numbers = {
    0: "huc12",
    1: "tpload_hp",
    2: "tpload_crop",
    3: "tpload_wooded",
    4: "tpload_open",
    5: "tpload_barren",
    6: "tpload_ldm",
    7: "tpload_mdm",
    8: "tpload_hdm",
    9: "tpload_wetland",
    10: "tpload_farman",
    11: "tpload_tiledrain",
    12: "tpload_streambank",
    13: "tpload_subsurface",
    14: "tpload_pointsource",
    15: "tpload_septics",
    16: "tnload_hp",
    17: "tnload_crop",
    18: "tnload_wooded",
    19: "tnload_open",
    20: "tnload_barren",
    21: "tnload_ldm",
    22: "tnload_mdm",
    23: "tnload_hdm",
    24: "tnload_wetland",
    25: "tnload_farman",
    26: "tnload_tiledrain",
    27: "tnload_streambank",
    28: "tnload_subsurface",
    29: "tnload_pointsource",
    30: "tnload_septics",
    31: "tssload_hp",
    32: "tssload_crop",
    33: "tssload_wooded",
    34: "tssload_open",
    35: "tssload_barren",
    36: "tssload_ldm",
    37: "tssload_mdm",
    38: "tssload_hdm",
    39: "tssload_wetland",
    40: "tssload_tiledrain",
    41: "tssload_streambank",
    42: "catchments"
}

huc12_column_numbers = {
    "huc12": 0,
    "tpload_hp": 1,
    "tpload_crop": 2,
    "tpload_wooded": 3,
    "tpload_open": 4,
    "tpload_barren": 5,
    "tpload_ldm": 6,
    "tpload_mdm": 7,
    "tpload_hdm": 8,
    "tpload_wetland": 9,
    "tpload_farman": 10,
    "tpload_tiledrain": 11,
    "tpload_streambank": 12,
    "tpload_subsurface": 13,
    "tpload_pointsource": 14,
    "tpload_septics": 15,
    "tnload_hp": 16,
    "tnload_crop": 17,
    "tnload_wooded": 18,
    "tnload_open": 19,
    "tnload_barren": 20,
    "tnload_ldm": 21,
    "tnload_mdm": 22,
    "tnload_hdm": 23,
    "tnload_wetland": 24,
    "tnload_farman": 25,
    "tnload_tiledrain": 26,
    "tnload_streambank": 27,
    "tnload_subsurface": 28,
    "tnload_pointsource": 29,
    "tnload_septics": 30,
    "tssload_hp": 31,
    "tssload_crop": 32,
    "tssload_wooded": 33,
    "tssload_open": 34,
    "tssload_barren": 35,
    "tssload_ldm": 36,
    "tssload_mdm": 37,
    "tssload_hdm": 38,
    "tssload_wetland": 39,
    "tssload_tiledrain": 40,
    "tssload_streambank": 41,
}

comid_column_numbers = {
    "comid": 0,
    "tploadrate_total": 1,
    "tploadate_conc": 2,
    "tnloadrate_total": 3,
    "tnloadrate_conc": 4,
    "tssloadrate_total": 5,
    "tssloadrate_conc": 6
}

comid_returned_column_numbers = {
    0: "comid",
    1: "tploadrate_total",
    2: "tploadate_conc",
    3: "tnloadrate_total",
    4: "tnloadrate_conc",
    5: "tssloadrate_total",
    6: "tssloadrate_conc"
}
